import { compose, withState } from 'recompose';
// import logo from '../../../assets/images'

import ListView from './ListView';

const listData = [
  {
    id: 1,
    name: 'Citizen',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Limited Edition',
    date: '02/02/2020',
    datetime: '12.00',
    status: 'NEW',
    badgeColor: '#3cd39f',
  },
  {
    id: 2,
    name: 'Weeknight',
    last: 'NEXT-LEVEL WEAR',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '05.00',
    timeFrom: true,
  },
  {
    id: 3,
    name: 'Mad Perry',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '11.00',
    timeFrom: true,
    status: 'SALE',
    badgeColor: '#ee1f78',
  },
  {
    id: 4,
    name: 'Citizen',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Limited Edition',
    date: '02/02/2020',
    datetime: '12.30',
    status: 'NEW',
    badgeColor: 'green',
  },
  {
    id: 5,
    name: 'Weeknight',
    last: 'NEXT-LEVEL WEAR',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '07.00',
    timeFrom: true,
  },
  {
    id: 6,
    name: 'Mad Perry',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '08.00',
    timeFrom: true,
    status: 'SALE',
    badgeColor: 'red',
  },
  {
    id: 7,
    name: 'Citizen',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Limited Edition',
    date: '02/02/2020',
    datetime: '09.00',
    status: 'NEW',
    badgeColor: '#3cd39f',
  },
  {
    id: 8,
    name: 'Weeknight',
    last: 'NEXT-LEVEL WEAR',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '10.00',
    timeFrom: true,
  },
  {
    id: 9,
    name: 'Mad Perry',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '14.00',
    timeFrom: true,
    status: 'SALE',
    badgeColor: '#ee1f78',
  },
  {
    id: 10,
    name: 'Citizen',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Limited Edition',
    date: '02/02/2020',
    datetime: '13.00',
    status: 'NEW',
    badgeColor: 'green',
  },
  {
    id: 11,
    name: 'Weeknight',
    last: 'NEXT-LEVEL WEAR',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '16.00',
    timeFrom: true,
  },
  {
    id: 12,
    name: 'Mad Perry',
    last: 'CITIZEN ECO-DRIVE',
    type: 'Office, prom or special parties is all dressed up',
    date: '02/02/2020',
    datetime: '15.00',
    timeFrom: true,
    status: 'SALE',
    badgeColor: 'red',
  },
];

export default compose(
  withState('tabIndex', 'setTabIndex', 0),
  // withState('tabs', 'setTabs', ['Grid', 'List 1', 'List 2']),
  withState('data', 'setData', listData),
)(ListView);
